### ISSUE TITLE
Sometimes Old apps being shipped

### ISSUE THREAD

**Issue by wanderlusttt** [nikgapps/config#3006]
@nikhilmenghani Hi, thanks for the good work.
However, one issue is that, inspite of making a new build, sometimes, I tend to get old apps and playstore keeps showing updates for the apps flashed resulting in usage of double data.. Is there anyway you could keep the apps updated?

**Comment by nikhilmenghani** [comment]
The app updating process is manual where we ship the tested apps. This is the reason why you don't always have the latest updated apps, however, when you build a custom build, you get the apps from the latest release (which may or may not have latest version of apps). 

Alternatively, it has been found that the updated version of apps usually are larger in size (double of original that is shipped) which also increases the zip size of NikGapps, larger the size of the zip, more difficult to release (deploy/build/upload). This is not a severity 1 issue since you can always update the apps from playstore (at the same time, get the priviliges you get by making the app a System/Privileged app)

**Comment by wanderlusttt** [comment]
Okay, thanks for the explanation.
