### ISSUE TITLE
Elite

### ISSUE THREAD

**Issue by cocka11** [nikgapps/config#8606]
Hi there, my name is Arbri and I'm the current maintainer for Lineages Android custom ROM for the Xiaomi Redmi 7/y3.
I would like to apply for creating recurring automatic "elite" builds using a custom config for my users.

As we do not ship Google Apps built-in, I've been testing several different packages, and have been testing & recommending NikGapps on multiple versions of Android, and as the preferred recommendation for Android 13 since MindTheGapps has had some permissions issues resulting in excessive battery drain early on.

I've been linking personal builds with a custom config file for several months now, in order to save time installing (since adb sideloading multiple packages to a slow, lineage-based recovery can be... onerous).

Huge thank you to Nikhil & team for the work on this project, and now for inviting me to test automatic package building!

**Comment by nikhilmenghani** [comment]
Hi @cocka11, cab you please specify the folder under which you'd like your builds be created?

**Comment by cocka11** [comment]
Arbri11

**Comment by nikgapps** [comment]
@cocka11 access has been provided to cocka11 folder, please proceed ahead with creating a pull request into elite/13/cocka11 folder with your new config.

**Comment by cocka11** [comment]
Thanks

**Comment by cocka11** [comment]
Where to download it nikgpapps.config for elite?

**Comment by nikhilmenghani** [comment]
@cocka11 noticed you were able to upload your config to elites folder and have a new build created.

Still waiting on the link I asked for reference. Please share the link to the post where you recommended NikGapps to your Rom, thanks!

**Comment by cocka11** [comment]
https://t.me/dhina17space

**Comment by nikgapps** [comment]
@cocka11 recommendation part is for Rom developers/maintainers and the recommendation from above link doesn't match the description you provided while applying for elites. Thus, you aren't really eligible for becoming an elite. However, since you've recommended it, you'll be offered an Elite build for 1 more release and then it will stop. There are more ways to contribute ([details here](https://nikgapps.com/misc/2023/06/08/NikGapps-Elites.html#how-to-join-nikgapps-elites)) - feel free to re-apply after you've contributed in one of the ways.
